const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:100,
            countInStock:4,
            brand:'Adidas',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:' Lactose free Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            countInStock:7,
            brand:'Lactose',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:' Lactose free Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            countInStock:0,
            brand:'Lactose',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'5',
            name:' Lactose free Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            countInStock:12,
            brand:'Lactose',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'6',
            name:' Nike slim pant',
            category:'Pants',
            image:'/images/p4.jpg',
            price:78,
            countInStock:9,
            brand:'Nike',
            rating:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'7',
            name:' Puma slim pant',
            category:'Pants',
            image:'/images/p5.jpg',
            price:65,
            countInStock:5,
            brand:'Puma',
            rating:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'8',
            name:' Adidas fit pant',
            category:'Pants',
            image:'/images/p6.jpg',
            price:139,
            countInStock:10,
            brand:'Adidas',
            rating:4.5,
            numReviews:15,
            description:'high quality product',
        },
    ]
}
export default data;